[project]
name = "scheme_interpreter"
version = "0.1.0"
description = "Scheme-like interpreter test project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"
